name: fprojects
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.0.5   # <-- Added provider
  http: ^0.13.5      # <-- Added http
  #google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add the assets section here
  # This will include all images under the 'assets/images' directory

  # Optionally add custom fonts if needed
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700
